### ISSUE TITLE
Example implementation

### ISSUE THREAD

**Issue by qume** [brycesenz/freeform#9]
Just wondering if you could put an example app in this repo, or possibly a separate repo? 

The gem looks great, including the high level doco, but having an example would be a super quick way for people to evaluate it more closely / quickly.

Thanks

**Comment by brycesenz** [comment]
Apologies for the late response.  I'll try to get a demo repo up when I have some time.  In the meantime, if you look in the "spec/dummy" folder, you'll see an example application that is used for testing, which shows off all of the ways to use the gem.

**Comment by qume** [comment]
Of course, spec, I should have checked there for testing code. Thanks very much.
